[".homebrew"]
    type = "git-repo"
    url = "https://github.com/Homebrew/brew"
[".emacs.d"]
    type = "git-repo"
    clone.args = [ "--depth", "1" ]
    url = "https://github.com/doomemacs/doomemacs"
